# Generated by github.com/da0x/mmpp
# Binary:
xg: .obj .obj/main.cpp.o .obj/x_block_measure.cpp.o .obj/x_options.cpp.o .obj/x_parallel.cpp.o .obj/x_probability.cpp.o .obj/x_process.cpp.o .obj/x_shell.cpp.o .obj/x_sort.cpp.o .obj/x_stdlib.cpp.o .obj/x_table.cpp.o .obj/x_tree.cpp.o .obj/x_uuid.cpp.o
	g++ -std=c++20 -L/opt/homebrew/lib -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer .obj/main.cpp.o .obj/x_block_measure.cpp.o .obj/x_options.cpp.o .obj/x_parallel.cpp.o .obj/x_probability.cpp.o .obj/x_process.cpp.o .obj/x_shell.cpp.o .obj/x_sort.cpp.o .obj/x_stdlib.cpp.o .obj/x_table.cpp.o .obj/x_tree.cpp.o .obj/x_uuid.cpp.o -o xg

.obj:
	mkdir .obj

.obj/main.cpp.o: main.cpp xg.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/main.cpp.o -c main.cpp

.obj/x_block_measure.cpp.o: x_block_measure.cpp x_block_measure.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_block_measure.cpp.o -c x_block_measure.cpp

.obj/x_options.cpp.o: x_options.cpp x_options.hpp x_table.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_options.cpp.o -c x_options.cpp

.obj/x_parallel.cpp.o: x_parallel.cpp x_parallel.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_parallel.cpp.o -c x_parallel.cpp

.obj/x_probability.cpp.o: x_probability.cpp x_probability.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_probability.cpp.o -c x_probability.cpp

.obj/x_process.cpp.o: x_process.cpp x_process.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_process.cpp.o -c x_process.cpp

.obj/x_shell.cpp.o: x_shell.cpp x_shell.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_shell.cpp.o -c x_shell.cpp

.obj/x_sort.cpp.o: x_sort.cpp x_sort.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_sort.cpp.o -c x_sort.cpp

.obj/x_stdlib.cpp.o: x_stdlib.cpp x_stdlib.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_stdlib.cpp.o -c x_stdlib.cpp

.obj/x_table.cpp.o: x_table.cpp x_tree.cpp x_table.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_table.cpp.o -c x_table.cpp

.obj/x_tree.cpp.o: x_tree.cpp x_tree.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_tree.cpp.o -c x_tree.cpp

.obj/x_uuid.cpp.o: x_uuid.cpp x_uuid.hpp
	g++ -std=c++20 -I/opt/homebrew/include -o .obj/x_uuid.cpp.o -c x_uuid.cpp

run: xg
	./xg

clean:
	rm -rfv .obj

install:
	sudo cp -v xg /usr/local/bin/

uninstall:
	sudo rm -v /usr/local/bin/xg
